### ISSUE TITLE
Linker error with wxEVT_DOWNLOAD_EVENT

### ISSUE THREAD

**Issue by BerndCirotzki** [OpenCPN/opencpn-libs#14]
... I'm trying to build somthing with asyncron download in a Plugin with using 
API116 the compile is OK, but there is a Linker Error to the OpenCPNlib ... tryed 116,113,118 everwhere the same : 
My code  : 

Connect(wxEVT_DOWNLOAD_EVENT,
    (wxObjectEventFunction)(wxEventFunction)&MyPlugin_pi::onDLEvent);

Error LNK2001 Unresolved external symbol ""int wxEVT_DOWNLOAD_EVENT" (?wxEVT_DOWNLOAD_EVENT@@3HA)".

... Is it a Lib error, or am I just too stupid for that ?

**Comment by nohal** [comment]
You forgot to point us to your code, so we don't know. But to start with make sure you define `MAKING_PLUGIN` for your plugin project as you are on the consumer side of https://github.com/OpenCPN/opencpn-libs/blob/main/api-18/ocpn_plugin.h#L1412-L1416

**Comment by BerndCirotzki** [comment]
Hi Pavel,
the define of "wxEVT_DOWNLOAD_EVENT" in opencpn_plugin.h is OK. The compile is OK.
but it't not found in the obj file of the lib.  "the Linker" 
... is any other Plugin using it ? so I would take a look at this code when it's not an error.
But don't hurry !

**Comment by nohal** [comment]
grib_pi and chartdldr_pi.

**Comment by BerndCirotzki** [comment]
... Oh, yes, I know ! But the are included in the OpenCPN main Code. 
that's not the same ! They are getting compiled with the main code.

**Comment by BerndCirotzki** [comment]
yes I have

04.03.2024 16:22:38 Pavel Kalian ***@***.***>:

**Comment by leamas** [comment]
... and:
```
$ nm -D opencpn | grep wxEVT_DOWNLOAD_EVENT
0000000001293c88 B wxEVT_DOWNLOAD_EVENT
```

That is, the symbol is included in the opencpn executable, so if any linking error should be on your side. 

Are you using any template like shipdriver for the plugin build, or are you trying to invent something on your own? In the latter case the problem is likely within your own build system.

**Comment by BerndCirotzki** [comment]
Thanks,
when you say it's in the "opencpn.lib" file and not only defined in the "opencpn_lib.h", ... The search continues.

**Comment by bdbcat** [comment]
Bernd...
o-charts_pi uses wxEVT_DOWNLOAD_EVENT
See ochartShop.cpp:6169

            Connect(wxEVT_DOWNLOAD_EVENT, (wxObjectEventFunction)(wxEventFunction)&shopPanel::onDLEvent);

https://github.com/bdbcat/o-charts_pi
branch sdt-1 is live.

**Comment by BerndCirotzki** [comment]
... Thanks to all very much,
I found the problem ... 
making 
#define MAKING_PLUGIN in the wrong File !!!!
erverything is working fine now.
