### ISSUE TITLE
Update README file

### ISSUE THREAD

**Issue by sebastien-rosset** [OpenCPN/opencpn-libs#18]
The README file states:

> opencpn-libs has been available as https://github.com/leamas/opencpn-libs. It has been moved to the new location https://github.com/opencpn/opencpn-libs. **During a transition window both of these locations will be kept in sync.**

> NOTE: Changes are done to the devel branch in github.com/opencpn/opencpn-libs. https://github.com/leamas/opencpn-libs should be considered being a read-only mirror.

I think that transition has been over for a while. Should this statement be removed?

**Comment by leamas** [comment]
> Should this statement be removed?

yes

**Comment by sebastien-rosset** [comment]
Thanks. I've raise #19 to remove the transition section and tried to improve the overview.
