### ISSUE TITLE
GL support is a mess.

### ISSUE THREAD

**Issue by leamas** [OpenCPN/opencpn-libs#6]
The OpenGL support in various libraries such as glu, libglu, libtess2, plugingk and what not is a mess and needs to be refactored.

**Comment by leamas** [comment]
In particular, plugingl/pidc depends on gl_private.h and glu. This is complicated on Android since it only supports GLES rather than the full GL stack. And including gl_private.h is basically a bad idea, this is an internal header.

**Comment by bdbcat** [comment]
Lets start here:
1.  Find a way to eliminate the need for gl_private.h
2. Make glu an explicit dependency of library opencpn-libs/plugingl

We can do #1 by the following patch to pidc.h:

```
#ifdef __ANDROID__
#include <qopengl.h>
//#include "GL/gl_private.h"
#define GL_GLEXT_LEGACY 1
#include "GL/gl.h"
#include "GL/glu.h"

```

#2  Not sure how to accomplish this best in opencpn-libs.
Thoughts?

**Comment by leamas** [comment]
The patch above still looks inconsistent to me. Android does not support GL, only GLES/GLES2. So including GL/whatever.h
on android seems buggy/odd/strange. 

Let's continue in zulip and return here when there are some conclusions.

**Comment by jongough** [comment]
Just tried using the new plugin_dc and am getting the following errors when building for android arm64:
```
-- Found Gettext: /usr/bin/msgmerge (found version "0.19.8.1") 
-- CMakeLists: Using JSON Schema validation - warning this changes the 'flavour' of the executable and it may not be compatible with OpenCPN
-- CMakeLists: Adding JSON Schema validation
CMake Warning (dev) at CMakeLists.txt:208 (target_sources):
  Policy CMP0076 is not set: target_sources() command converts relative paths
  to absolute.  Run "cmake --help-policy CMP0076" for policy details.  Use
  the cmake_policy command to set the policy and suppress this warning.

  An interface source of target "testplugin_pi" has a relative path.
This warning is for project developers.  Use -Wno-dev to suppress it.

-- CMakeLists: Adding target link libraries to testplugin_pi
-- Using bundled tinyxml
-- Could NOT find OpenGL (missing: OPENGL_opengl_LIBRARY OPENGL_glx_LIBRARY OPENGL_INCLUDE_DIR) 
CMake Warning at opencpn-libs/plugin_dc/CMakeLists.txt:39 (message):
  Cannot locate a OpenGL stack


-- CMakeLists: lib-name: libtestplugin_pi.so
```
and
```
-- CMakeLists: include directories:
-- CMakeLists: dir='/home/circleci/project/OCPNAndroidCommon-master/wxWidgets/include'
-- CMakeLists: dir='/home/circleci/project/OCPNAndroidCommon-master/wxWidgets/libarm64/wx/include/arm-linux-androideabi-qt-unicode-static-3.1'
-- CMakeLists: dir='/home/circleci/project/OCPNAndroidCommon-master/qt5/build_arm64_O3/qtbase/include/QtTest'
-- CMakeLists: dir='/home/circleci/project/OCPNAndroidCommon-master/qt5/build_arm64_O3/qtbase/include/QtOpenGL'
-- CMakeLists: dir='/home/circleci/project/OCPNAndroidCommon-master/qt5/build_arm64_O3/qtbase/include/QtGui'
-- CMakeLists: dir='/home/circleci/project/OCPNAndroidCommon-master/qt5/build_arm64_O3/qtbase/include/QtWidgets'
-- CMakeLists: dir='/home/circleci/project/OCPNAndroidCommon-master/qt5/build_arm64_O3/qtbase/include/QtCore'
-- CMakeLists: dir='/home/circleci/project/OCPNAndroidCommon-master/qt5/build_arm64_O3/qtbase/include'
-- CMakeLists: dir='/home/circleci/project/include'
-- CMakeLists: dir='/home/circleci/project/OCPNAndroidCommon-master/wxWidgets/include'
-- CMakeLists: dir='/home/circleci/project/OCPNAndroidCommon-master/wxWidgets/libarm64/wx/include/arm-linux-androideabi-qt-unicode-static-3.1'
-- CMakeLists: dir='/home/circleci/project/OCPNAndroidCommon-master/qt5/build_arm64_O3/qtbase/include/QtTest'
-- CMakeLists: dir='/home/circleci/project/OCPNAndroidCommon-master/qt5/build_arm64_O3/qtbase/include/QtOpenGL'
-- CMakeLists: dir='/home/circleci/project/OCPNAndroidCommon-master/qt5/build_arm64_O3/qtbase/include/QtGui'
-- CMakeLists: dir='/home/circleci/project/OCPNAndroidCommon-master/qt5/build_arm64_O3/qtbase/include/QtWidgets'
-- CMakeLists: dir='/home/circleci/project/OCPNAndroidCommon-master/qt5/build_arm64_O3/qtbase/include/QtCore'
-- CMakeLists: dir='/home/circleci/project/OCPNAndroidCommon-master/qt5/build_arm64_O3/qtbase/include'
-- CMakeLists: dir='/home/circleci/project/build/CMakeFiles/include'
-- CMakeLists: dir='/home/circleci/project/include'
-- CMakeLists: dir='/home/circleci/project/src'
-- CMakeLists: dir='/home/circleci/project/libs/glshim/include/GLES'
-- Configuring done
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    Qt_Build
```
So not sure what to do now.

I have added 
```
    add_subdirectory(opencpn-libs/plugin_dc)
    target_link_libraries(${PACKAGE_NAME} ocpn::plugin-dc)
```
to replace
```
    add_subdirectory(opencpn-libs/plugingl)
    target_link_libraries(${PACKAGE_NAME} ocpn::plugingl)

```
and removed this from PluginConfigure.cmake, starting line 495:
```
        message(STATUS "${CMLOC}    Adding local GLU")
        if (WIN32)
            add_subdirectory(opencpn-libs/WindowsHeaders)
            target_link_libraries(${PACKAGE_NAME} windows::headers)
        endif(WIN32)

        add_subdirectory(opencpn-libs/glu)
        message(STATUS "${CMLOC}PACKAGE_NAME: ${PACKAGE_NAME}")
        target_link_libraries(${PACKAGE_NAME} ocpn::glu_static)
        add_definitions(-DocpnUSE_GL)

        set(wxWidgets_USE_LIBS ${wxWidgets_USE_LIBS} gl)
        message(STATUS "${CMLOC}    Revised GL Lib (with local): " ${OPENGL_LIBRARIES})
```

This is all based on the testplugin_pi that Rick has in his repository.

**Comment by jongough** [comment]
Further to the above building for android armhf give:
```
-- CMakeLists: Adding target link libraries to testplugin_pi
-- Using bundled tinyxml
-- Could NOT find OpenGL (missing: OPENGL_opengl_LIBRARY OPENGL_glx_LIBRARY OPENGL_INCLUDE_DIR) 
CMake Warning at opencpn-libs/plugin_dc/CMakeLists.txt:39 (message):
  Cannot locate a OpenGL stack
```

**Comment by bdbcat** [comment]
Jon...
In CMakeLists.txt, we want to say this (around line 100)

`set(USE_LOCAL_GLU FALSE)
`

In fact, with new plugin-dc, there should never be any need to use "LOCAL_GLU" flag.  I am proposing to eliminate that option, as well as all supporting logic in PluginConfigure.cmake, as a simplification.

I sent you email on this, maybe you missed it.
If you agree, I will post a PR to Ricks' repo, with the fully edited implementation.

**Comment by jongough** [comment]
Yep, posting to Ricks repository is fine, I can then incorporate the changes into my version which I think is a little ahead of Ricks for MSVC and `circleci local` processing. I am doing my testing using `circleci local` due to a slow internet connection.

**Comment by bdbcat** [comment]
Did your local build work with 
`set(USE_LOCAL_GLU FALSE) `
?

**Comment by jongough** [comment]
This is the command I am using for the local builds:
```
circleci local execute  build-android-armhf -e CIRCLECI_LOCAL=true -v "/home/jon/opencpn/circleci-output:/home/circleci/circleci-output" -v "/home/jon/opencpn/circleci-cache:/home/circleci/circleci-cache" -e LOCAL_DEPLOY -e CLOUDSMITH_API_KEY="123"
```
and for arm64 just substitute that in to the execute. The `circleci-output` is for the package files locally and the `circleci-cache` is for storing the master.zip and apt cache settings.

**Comment by jongough** [comment]
I am trying a build with the `USE_LOCAL_GLU FALSE` at the moment.

**Comment by bdbcat** [comment]
I mean this error:

`  Cannot locate a OpenGL stack`

Should be fixed by the USE_LOCAL_GLU FALSE setting.
Please confirm.

**Comment by jongough** [comment]
Having internet issues, i.e. slow and not finding servers (hence using local builds). I will let you know when I get a run to happen.

**Comment by bdbcat** [comment]
OK.

**Comment by jongough** [comment]
Run happened and still have same issue. I assume using:
```
    add_subdirectory(opencpn-libs/plugin_dc)
    target_link_libraries(${PACKAGE_NAME} ocpn::plugin-dc)
```
is the correct way to incorporate the new changes?

**Comment by jongough** [comment]
armhf will build, arm64 does not.

**Comment by bdbcat** [comment]
I am working on testplugin updates now, should have new code in Ricks repo in 30 minutes.

**Comment by jongough** [comment]
Sorry, I had a typo in the arm64 script, got it fixed now and amr64 is building.

**Comment by bdbcat** [comment]
Jon...
PR made and accepted into Rick's testplugin_pi repo, master branch

For reference, here are the basic changes I made in the FE2 template files.  I think you have already made the required changes to CMakeLists.txt

```

1.  update/add template files
        ci/circleci-build-android-arm64.sh
        ci/circleci-build-android-armhf.sh

        cmake/android-aarch64-toolchain.cmake
        cmake/android-armhf-toolchain.cmake
        cmake/PluginConfigure.cmake

        .circleci/config.yml

2.  Edit/update cmakelists

        a.
        if (WIN32)
            add_subdirectory(opencpn-libs/WindowsHeaders)
                target_link_libraries(${PACKAGE_NAME} windows::headers)
        endif (WIN32)

        b.
        add_subdirectory(opencpn-libs/plugin_dc)
        target_link_libraries(${PACKAGE_NAME} ocpn::plugin-dc)

3.  Update submodule opencpn-libs

    $ git submodule update --remote --merge opencpn-libs
    $ git add opencpn-libs
    $ git commit -m "Update opencpn-libs submodule"
    $ git push origin master
```

I also made small changes to one source file "include/testplugin_pi.h".

The build is started on CCI:
https://github.com/rgleason/testplugin_pi/runs/18168759221

Good Luck

**Comment by jongough** [comment]
What is the reason to install a python pip cmake, the android version is 3.16 and the python version is 3.22? It

The changes are now incorportated and I am just building locally to make sure it all works for me.

**Comment by bdbcat** [comment]
We now use a CMake toolchain file to build for Android.  We do this in order to use the proper sysroot headers for GLES2, from the Android NDK.
Proper support for Android toolchain requires a pretty recent CMake version, which is not available in the base build-bot system load.  Python pip will give us a sufficiently recent CMake to proceed.

**Comment by jongough** [comment]
Just building the master for 1.0.276.0 . All going well at the moment.

**Comment by jongough** [comment]
Just trying to build OD with the latest opencpn-libs and it would appear that pidc.cpp defines checkGLError in the cpp code and not in the header, so it is not accessible. Many of the items in OD use this to validate that the gl stuff is correct. OD used to have this defined in ODUtils.h . Can pidc.cpp be amended to define this in pidc.h such that other code can use it?

**Comment by jongough** [comment]
I have installed and run OD within OCPN 5.9.0 and it mostly works. Dialog boxes seem 'strange' and buttons do not change colours. So it will need some more investigation. But basically OD is working within OCPN using opencpn-libs.
I did the build using circleci local for the  jammy environment creating the installable tar.gz, just for info.

**Comment by leamas** [comment]
I have disabled the use of glu/,  opencpn-glu/ and libglu/, they more or less empty placeholders breaking the build with a proper error message if used. 

Devel branch for now. This means that the mess is sorted out, everything needed for a plugin DC including the GL stuff is now in plugin_dc besides libtess. 

Closing. Please file new specific issues as they pop up.

**Comment by leamas** [comment]
>  Can pidc.cpp be amended to define this in pidc.h such that other code can use it

Sure, please make a PR

**Comment by jongough** [comment]
Have created a pull request for pidc.h in the devel branch.

**Comment by leamas** [comment]
@bdbcat 

Here: https://github.com/OpenCPN/opencpn-libs/pull/8

Since you are on this....

**Comment by bdbcat** [comment]
Jon...
PR accepted to "devel" branch.

**Comment by leamas** [comment]
@jongough : you don't need to wait for this to be merged into main to test, you can use the devel branch as well. Of course, this is by definition unstable but current state is not that bad. Do:

     $ cd opencpn-libs
     $ git remote update origin
     $ git checkout main
     $ git fetch -f origin devel:devel
     $ git checkout devel
     $ cd ..
     $ git add opencpn-libs
     $ git commit  "updating opencpn-libs to latest devel"

Not all steps are always necessary, this is the "better safe than sorry" approach. Still, you should get the idea if you not already are into this.

**Comment by jongough** [comment]
I was being cautious as due the changes being made by others I didn't want to cause issues.

**Comment by leamas** [comment]
No  need, the delta against main is really small right now.
